name: Test automatique
on: 
  push:
    branches:
        - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
        - name: recuperation name
          uses: actions/checkout@v4

        - name: install node
          uses:  actions/setup-node@v4
          with:
            node-version: '20'

        - run: npm test
        - run: echo "tous les tests sont réussi"